exports.fonts = [
    { label: 'Poppins' },
    { label: 'Roboto' },
    { label: 'Lato' },
    { label: 'Merriweather' },
    { label: 'Inter' },
    { label: 'Playfair Display' },
    { label: 'DM Sans' },
    { label: 'Open Sans' },
    { label: 'Raleway' },
    { label: 'Ubuntu' },
    { label: 'Manrope' },
    { label: 'Quicksand' },
    { label: 'Rubik' },
    { label: 'Work Sans' },
    { label: 'Nunito' },
    { label: 'PT Sans' },
    { label: 'Fira Sans' },
    { label: 'Cabin' },
    { label: 'Bebas Neue' },
    { label: 'Space Grotesk' },
];
